server:
  port: 8701  # 서비스 port
spring:
  application:
    name: customer-service # 서비스명
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    preferIpAddress: false # 서비스간 통신 시 hostname 보다 ip 를 우선 사용 함